spring:
  jpa.hibernate:
      ddl-auto: update
  datasource:
    url: @database.url@
    username: @database.user@
    password: @database.password@
    driver-class-name: com.mysql.jdbc.Driver

server.port: @server.port@